version: "3.6"
networks:
  backend:
  frontend:
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - backend
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    networks:
      - backend
      - frontend
  proxy:
    image: zwilson/proxy
    restart: always
    build: .
    networks:
      - frontend
    ports:
      - 80:80
    volumes:
      - ./configs/nginx/kibana.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    command: nginx-debug -g 'daemon off;'
volumes:
  elasticsearch_data:
