version: "3.6"
networks:
  backend:
  frontend:
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - backend
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    networks:
      - backend
      - frontend
  proxy:
    image: nginx
    restart: always
    build: .
    ports:
      - 80:80
    volumes:
      - ./configs/nginx/kibana.conf:/etc/nginx/conf.d/mysite.template
      - ./logs/nginx:/var/log/nginx
    environment:
      USERNAME: admin
      PASSWORD: password
      NGINX_HOST: localhost
    networks:
      - frontend
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx-debug -g 'daemon off;'" # WARNING: NOT FOR PROD
volumes:
  elasticsearch_data:
