version: "3.6"
configs:
  kibana.conf:
      file: ./configs/nginx/kibana.conf
networks:
  backend:
    driver: overlay
    attachable: true
    external: true
  frontend:
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      xpack.monitoring.collection.enabled: "true"
    networks:
      - backend
    volumes:
      - type: volume
        source: elasticsearch_data
        target: /usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    networks:
      - backend
      - frontend
    environment:
      server.host: cloud.retool.solutions
  nginx:
    image: nginx
    ports:
      - 80:80
    env_file: dev.env
    configs:
      - source: kibana.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - frontend
volumes:
  elasticsearch_data:
