version: "3.6"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
      - 9200:9200
    volumes:
      - type: volume
        source: elasticsearch_data
        target: /usr/share/elasticsearch/data
    environment:
      xpack.monitoring.collection.enabled: "true"
  logstash:
    image: docker.elastic.co/logstash/logstash:6.3.2
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
volumes:
  elasticsearch_data:
  items:
